name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ['2.7', '3.0', '3.1', 'head']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake ci
